### ISSUE TITLE
Missing required packages in $RequiredPackets

### ISSUE THREAD

**Issue by rmueck** [speefak/rear-backup#1]
I think two packages are missing in `RequiredPackets`. As far i can see `pv` and `lshw` are required as well.

`./rear-backup.sh: line 394: lshw: command not found` and  in line 503
 `dd if=${ISO2USBSourcefile} | pv ${ISO2USBSourcefile} | dd of=${USBTargetDevicePath} status=none conv=fdatasync oflag=sync bs=2M`

**Comment by speefak** [comment]
You are right, lshw and pv are missing from the required packages list. I added both to the RequiredPackets var.

**Comment by rmueck** [comment]
Thank you!
