### ISSUE TITLE
Limitations of ISO size

### ISSUE THREAD

**Issue by rmueck** [speefak/rear-backup#2]
When i was trying to create an iso (-cib) recovery system, i got the following error:

~~~sh
# ./rear-backup.sh -cib
 SSH connection user@192.168.11.11 established ✔
Relax-and-Recover 2.7 / Git
Running rear mkbackup (PID 46031 date 2024-08-17 13:45:09)
Using log file: /var/log/rear/rear-debian.log
[SNIP]
.
.
Creating recovery/rescue system initramfs/initrd initrd.cgz with gzip default compression
Created initrd.cgz with gzip default compression (182003256 bytes) in 21 seconds
Making backup (using backup method NETFS)
Creating tar archive '/var/tmp/rear.JkZZDII34XZx29c/tmp/isofs/backup/backup.tar.gz'
Archived 3951 MiB [avg 47048 KiB/sec] OK
Archived 3951 MiB in 88 seconds [avg 45979 KiB/sec]
Making ISO image
ERROR: File for ISO backup.tar.gz size 4146654939 greater or equal **ISO_FILE_SIZE_LIMIT=2147483648**
Some latest log messages since the last called script 820_create_iso_image.sh:
  2024-08-17 13:47:17.732710143 Starting '/usr/bin/xorrisofs'
  2024-08-17 13:47:17.735668438 Making ISO image
Some messages from /var/tmp/rear.JkZZDII34XZx29c/tmp/rear.mkbackup.stdout_stderr since the last called script 820_create_iso_image.sh:
  2147483648
  4519276
  4146654939
Use debug mode '-d' for some debug messages or debugscript mode '-D' for full debug messages with 'set -x' output
Aborting due to an error, check /var/log/rear/rear-debian.log for details
Exiting rear mkbackup (PID 46031) and its descendant processes ...
Running exit tasks
Terminated
~~~

Maybe it is possible to include a switch or variable to adjust `ISO_FILE_SIZE_LIMIT` for example in `WriteRearConfigAdditional () {`
I my opinion it is essntial to adjust this limitation b/c a fresh installed Linux (e.g Mint/xfce) will consume more then 2GB compressed space.

Thank you!

**Comment by speefak** [comment]
The actual limit is 4,7 GB (iso-level-3 parameter), but the message shows 2GB as limit, even if the mage size is limited to 4,7 GB. I`ll built a (auto) switch that raises the limitsize if needed. Images Larger than 4,7 GB sometimes dont start or cause other error. 

But to avoid any errors its better to split the image file to 2GB parts if this is supported by rear backup.

**Comment by speefak** [comment]
The actual limit should be 4,7 GB (iso-level-3 parameter), but the message shows 2GB as limit, even if the image size is limited to 4,7 GB. Images Larger than 4,7 GB sometimes dont start or cause other errors. Please check if REAR runs on your system using the ISO_FILE_SIZE_LIMIT=0 which disables the limitation completely. 

But to avoid any errors its better to split the image file to 2GB parts if this is supported by rear backup.

I added an adjustment/disable via ISO_FILE_SIZE_LIMIT in WriteRearConfigAdditional (). It works with large images, tested up to 20 GB.

file_size_limit is disabled by:

281		# disable iso filesize limit => 0 (default 2 GB ISO_FILE_SIZE_LIMIT=2147483648)
282		ISO_FILE_SIZE_LIMIT=0

Backup/Restore (6,7GB) GB works
Backup/Restore (13GB) GB works
Backup/Restore (20GB) GB works

I dont know if the warnings in the rear config files for writing files larger than 2/4GB to ISO FS is only for writing on CD/DVD. Backup/Restore works with a 20GB image included in the ISO backup.

**Comment by speefak** [comment]
The actual limit should be 4,7 GB (iso-level-3 parameter), but the message shows 2GB as limit, even if the image size is limited to 4,7 GB. Images Larger than 4,7 GB sometimes dont start or cause other errors. Please check if REAR runs on your system using the ISO_FILE_SIZE_LIMIT=0 which disables the limitation completely. 

But to avoid any errors its better to split the image file to 2GB parts if this is supported by rear backup.

I added an adjustment/disable via ISO_FILE_SIZE_LIMIT in WriteRearConfigAdditional (). It works with large images, tested up to 20 GB.

EDIT: 

file_size_limit is disabled by:

281		# disable iso filesize limit => 0 (default 2 GB ISO_FILE_SIZE_LIMIT=2147483648)
282		ISO_FILE_SIZE_LIMIT=0

Backup/Restore (6,7GB) GB works
Backup/Restore (13GB) GB works
Backup/Restore (20GB) GB works

I dont know if the warnings in the rear config files for writing files larger than 2/4GB to ISO FS is only for writing on CD/DVD. Backup/Restore works with a 20GB image included in the ISO backup.
